### PR TITLE
Wrap `this.col` in promise(can be accessed before initialized in my case) + refactoring to ES6, mocha tests

### PR DESCRIPTION
**Pull request by ndelitski**
Hi there! I have used your package in my project and found annoying that it always crushes when trying to access collection before it is initalized...(i'm using webpack with hot updates, browsersync, and nodemon, so when server runs browser send request simultaneously and in most cases i got error). Thats why i wrapped collection into a promise. and btw rewrite in ES6 and mocha tests.
Passes tests, so please review.

### CODE REVIEW

**Comment by freakycue** [comment]
@ndelitski, looks good, except why the last test is commented?

**Comment by ndelitski** [comment]
same test doesn't work in your version for me, debugging it show error on `db.authenticate` stage, have an idea?

**Comment by freakycue** [comment]
@ndelitski, everything looks fine in the code. Maybe something with your local configuration?

**Comment by ndelitski** [comment]
i'm using 3.0.3 mongo locally in docker container with default configuration, could you uncomment last line and try on your machine?

**Comment by ndelitski** [comment]
seems an issue was resolved, but i found that auth test pass for ANY password

**Comment by freakycue** [comment]
@ndelitski, I'll take a look on tests today evening. What was as issue?

**Comment by freakycue** [comment]
@ndelitski, auth tests issues was fixed in another pull request

**Comment by ndelitski** [comment]
@freakycue merged with last version

**Comment by freakycue** [comment]
@ndelitski, everything works fine, good work!

**Pull request merged**
